version: '3.8'

services:
  camera:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /run/udev:/run/udev:ro
    ports:
      - "5000:5000"
    restart: always
    privileged: true